// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using ProtractorBuilder.Protractor.Common;
using ProtractorBuilder.Protractor.DbContext;
using System;

namespace ProtractorBuilder.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestCase", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("Log");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("TestSuiteId");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestCaseStep", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActionSequence");

                    b.Property<string>("CaseId");

                    b.Property<string>("CurrentFailedElement");

                    b.Property<string>("LastSuccessfulElement");

                    b.Property<int>("Locator");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("ResultFromId");

                    b.Property<string>("TestCaseId");

                    b.Property<string>("TestSuiteId");

                    b.Property<string>("TestSuiteId1");

                    b.Property<string>("TestSuiteId2");

                    b.Property<string>("TestSuiteId3");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ResultFromId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId1");

                    b.HasIndex("TestSuiteId2");

                    b.HasIndex("TestSuiteId3");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestModule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestSuite", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("TestModuleId");

                    b.HasKey("Id");

                    b.HasIndex("TestModuleId");

                    b.ToTable("Suites");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestCase", b =>
                {
                    b.HasOne("ProtractorBuilder.Protractor.Common.TestSuite")
                        .WithMany("Cases")
                        .HasForeignKey("TestSuiteId");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestCaseStep", b =>
                {
                    b.HasOne("ProtractorBuilder.Protractor.Common.TestCaseStep", "ResultFrom")
                        .WithMany()
                        .HasForeignKey("ResultFromId");

                    b.HasOne("ProtractorBuilder.Protractor.Common.TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId");

                    b.HasOne("ProtractorBuilder.Protractor.Common.TestSuite")
                        .WithMany("AfterAll")
                        .HasForeignKey("TestSuiteId");

                    b.HasOne("ProtractorBuilder.Protractor.Common.TestSuite")
                        .WithMany("AfterEach")
                        .HasForeignKey("TestSuiteId1");

                    b.HasOne("ProtractorBuilder.Protractor.Common.TestSuite")
                        .WithMany("BeforeAll")
                        .HasForeignKey("TestSuiteId2");

                    b.HasOne("ProtractorBuilder.Protractor.Common.TestSuite")
                        .WithMany("BeforeEach")
                        .HasForeignKey("TestSuiteId3");
                });

            modelBuilder.Entity("ProtractorBuilder.Protractor.Common.TestSuite", b =>
                {
                    b.HasOne("ProtractorBuilder.Protractor.Common.TestModule")
                        .WithMany("Suites")
                        .HasForeignKey("TestModuleId");
                });
#pragma warning restore 612, 618
        }
    }
}
